language: python
sudo: required
dist: xenial
python: "3.7"
env:
  global:
    - DEPLOY_SERVER_ADDRESS=catalist.thefed.xyz
    - DEPLOY_SERVER_USER=hackathon
    - DEPLOY_SERVER_PATH=/home/hackathon/catalist

before_install:
- openssl aes-256-cbc -K $encrypted_04fb17de469d_key -iv $encrypted_04fb17de469d_iv
  -in deploy_key.enc -out ../deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 ./deploy_key
- echo -e "Host $DEPLOY_SERVER_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- ssh-add ./deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master

