language: python
sudo: required
dist: xenial
python: "3.7"
env:
  global:
    - DEPLOY_SERVER_ADDRESS=catalist.thefed.xyz
    - DEPLOY_SERVER_USER=hackathon
    - DEPLOY_SERVER_PATH=/home/hackathon/catalist

script:
- echo "No tests to run"

addons:
  ssh_known_hosts: $DEPLOY_SERVER_ADDRESS

before_install:
- openssl aes-256-cbc -K $encrypted_04fb17de469d_key -iv $encrypted_04fb17de469d_iv
  -in deploy_key.enc -out /tmp/deploy_key -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_key
- ssh-add /tmp/deploy_key

deploy:
  provider: script
  skip_cleanup: true
  script: bash scripts/deploy.sh
  on:
    branch: master

